source "https://rubygems.org"

group :jekyll_plugins do
  gem "github-pages"
  gem 'jekyll-include-cache'
  gem "jekyll-paginate-v2"
  gem "jekyll-redirect-from"
  gem "jekyll-feed"
end

gem "minimal-mistakes-jekyll"
